services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:q1J9
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: taskflow
      DB_USERNAME: admin
      DB_PASSWORD: secretadmin
      
      

  db:
    image: postgres:15
    container_name: postgre_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretadmin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
    postgres_data: